language: python

python:
  - "3.5"

services:
  - sqlite3

install:
  - pip install -r requirements/requirements.txt

before_script:
  - cp ecom_merci/.env_test ecom_merci/.env
  - ./check_migrations.sh
  - flake8 --exclude='ipython_log.py*,migrations,templates, manage.py' .

script:
  - ./manage.py migrate
  - py.test --create-db
